### ISSUE TITLE
Script could not be loaded while querying index

### ISSUE THREAD

**Issue by sa2423** [StaySense/fast-cosine-similarity#10]
I was able to install the plugin successfully after following instructions on the README.

However, when I try to query the index using the given query format, I get the following error:
`RequestError(400, search_phase_execution_exception, script_score: the script could not be loaded)`

How should I resolve this in order to query the index using cosine similarity?

**Comment by sa2423** [comment]
ES Version: 6.4.1

I am using the Python Elasticsearch Client and the base64 encoded vector is passed through a function. 

`es = Elasticsearch(['http://127.0.0.1:9200/'])`

`	staysense_search_payload = {
  		"query": {
    	"function_score": {
    	"boost_mode" : "replace",
        	"functions": [
          			{
            		"script_score": {
              			"script": {
                  			"source": "staysense",
                  			"lang" : "fast_cosine",
                  			"params": {
                      			"field": "embeddedVector",
                      			"cosine": "true",
                      			"encoded_vector" : vector, 
                  				}
              				}	
            			}
          			}
        		]
    		}
  		}
	}
`

`res = es.search(index="test", body=staysense_search_payload)`

**Comment by wmelton** [comment]
Almost definitely an issue with your query. 

The parameter value for `cosine` must be of type `boolean` not `string`.

**Comment by sa2423** [comment]
Thank you, the query works now.
