### ISSUE TITLE
Cannot Seem to Load StaySense Script

### ISSUE THREAD

**Issue by dpalbrecht** [StaySense/fast-cosine-similarity#15]
I am trying to use this plugin with ES 6.4.1, but am getting an error of: `elasticsearch.exceptions.RequestError: RequestError(400, 'search_phase_execution_exception', 'script_score: the script could not be loaded')` during loading of my Flask app. I have, to my knowledge followed the installation instructions correctly and have `elasticsearch-fast-cosine-similarity` in my `plugins` folder of ES.

I map the feature like so:
```
"name_embedding_encoded": {
                            "type": "binary",
                            "doc_values": True
                          }
```

Create the query:
```
name_embedding_query = {
                                "function_score": {
                                "boost_mode" : "replace",
                                    "functions": [
                                      {
                                        "script_score": {
                                          "script": {
                                              "source": "staysense",
                                              "lang" : "fast_cosine",
                                              "params": {
                                                  "field": "name_embedding_encoded",
                                                  "cosine": True,
                                                  "encoded_vector": term
                                              }
                                          }
                                        }
                                      }
                                    ]
                                }
                              }
```

and then make the query:
```
client = Elasticsearch()
s = Search(using=client, index=INDEX_NAME, doc_type=DOC_TYPE)
docs = s.query(name_embedding_query)[:count].execute()
```

But cannot seem to get the script to load. What am I missing?

**Comment by dpalbrecht** [comment]
Fixed: I was not passing in base64 encoded vectors properly. The error message is quite misleading.

**Comment by wmelton** [comment]
@dpalbrecht - Glad you were able to get this resolved. Agree - the error messages are not clear.

**Comment by gabrielcustodio** [comment]
> Fixed: I was not passing in base64 encoded vectors properly. The error message is quite misleading.

What was wrong?

**Comment by dpalbrecht** [comment]
@gabrielcustodio The vectors were not base64 encoded, but the error message did not describe that as the problem.

**Comment by gabrielcustodio** [comment]
Got it, thanks!

Em qui, 16 de jan de 2020 13:40, David Albrecht <notifications@github.com>
escreveu:
