### ISSUE TITLE
script_lang not supported [fast_cosine]

### ISSUE THREAD

**Issue by stevenbinhu21** [StaySense/fast-cosine-similarity#4]
Hi, 

I am getting this error:  **script_lang not supported [fast_cosine]** after successfully build and install to Elasticsearch v6.4.2.   I only changed es version in pom.xml as suggested. 
Could you please help?  

Also I have tried ES official examples score-expert-script, and it ouputs a similar error:  **script_lang not supported [expert_scripts]**. 

Please forgive me for being quite new to Elasticsearch,  I return this lang name in the getType() function in the nested FastCosineSimilarityEngine class,  it seems nothing you write there works.  

`  

    private static class FastCosineSimilarityEngine implements ScriptEngine {
    //The normalized vector score from the query
    //
    double queryVectorNorm;

    @Override
    public String getType() {
        return "fast_cosine";
    }
`
ES log if it helps

 Caused by: org.elasticsearch.index.query.QueryShardException: script_score: the script could not be loaded                                                                                                                                                      
4530 >---at org.elasticsearch.index.query.functionscore.ScriptScoreFunctionBuilder.doToFunction(ScriptScoreFunctionBuilder.java:99) ~[elasticsearch-6.4.2.jar:6.4.2]                                                                                                 
4531 >---at org.elasticsearch.index.query.functionscore.ScoreFunctionBuilder.toFunction(ScoreFunctionBuilder.java:138) ~[elasticsearch-6.4.2.jar:6.4.2]                                                                                                              
4532 >---at org.elasticsearch.index.query.functionscore.FunctionScoreQueryBuilder.doToQuery(FunctionScoreQueryBuilder.java:298) ~[elasticsearch-6.4.2.jar:6.4.2]                                                                                                     
4533 >---at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:98) ~[elasticsearch-6.4.2.jar:6.4.2]                                                                                                                                
4534 >---at org.elasticsearch.index.query.QueryShardContext.lambda$toQuery$2(QueryShardContext.java:305) ~[elasticsearch-6.4.2.jar:6.4.2]                                                                                                                            
4535 >---at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:317) ~[elasticsearch-6.4.2.jar:6.4.2]                                                                                                                                     
4536 >---at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:304) ~[elasticsearch-6.4.2.jar:6.4.2]                                                                                                                                     
4537 >---at org.elasticsearch.search.SearchService.parseSource(SearchService.java:724) ~[elasticsearch-6.4.2.jar:6.4.2]                                                                                                                                              
4538 >---at org.elasticsearch.search.SearchService.createContext(SearchService.java:575) ~[elasticsearch-6.4.2.jar:6.4.2]                                                                                                                                            
4539 >---at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:551) ~[elasticsearch-6.4.2.jar:6.4.2]                                                                                                                                      
4540 >---at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:347) ~[elasticsearch-6.4.2.jar:6.4.2]                                                                                                                                        
4541 >---at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:333) ~[elasticsearch-6.4.2.jar:6.4.2]                                                                                                                                             
4542 >---at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:329) ~[elasticsearch-6.4.2.jar:6.4.2]                                                                                                                                             
4543 >---at org.elasticsearch.search.SearchService$3.doRun(SearchService.java:1019) ~[elasticsearch-6.4.2.jar:6.4.2]                                                                                                                                                 
4544 >---at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:723) ~[elasticsearch-6.4.2.jar:6.4.2]                                                                                                  
4545 >---at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.4.2.jar:6.4.2]                                                                                                                                 
4546 >---at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41) ~[elasticsearch-6.4.2.jar:6.4.2]                                                                                                                                     
4547 >---at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.4.2.jar:6.4.2]                                                                                                                                 
4548 >---at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_191]                                                                                                                                                           
4549 >---at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_191]                                                                                                                                                           
4550 >---at java.lang.Thread.run(Thread.java:745) [?:1.8.0_191]                                                                                                                                                                                                      
4551 Caused by: java.lang.IllegalArgumentException: script_lang not supported [fast_cosine]                                                                                                                                                                          
4552 >---at org.elasticsearch.script.ScriptService.getEngine(ScriptService.java:240) ~[elasticsearch-6.4.2.jar:6.4.2]                                                                                                                                                
4553 >---at org.elasticsearch.script.ScriptService.compile(ScriptService.java:294) ~[elasticsearch-6.4.2.jar:6.4.2]                                                                                                                                                  
4554 >---at org.elasticsearch.index.query.functionscore.ScriptScoreFunctionBuilder.doToFunction(ScriptScoreFunctionBuilder.java:95) ~[elasticsearch-6.4.2.jar:6.4.2]                                                                                                 
4555 >---at org.elasticsearch.index.query.functionscore.ScoreFunctionBuilder.toFunction(ScoreFunctionBuilder.java:138) ~[elasticsearch-6.4.2.jar:6.4.2]                                                                                                              
4556 >---at org.elasticsearch.index.query.functionscore.FunctionScoreQueryBuilder.doToQuery(FunctionScoreQueryBuilder.java:298) ~[elasticsearch-6.4.2.jar:6.4.2]                                                                                                     
4557 >---at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:98) ~[elasticsearch-6.4.2.jar:6.4.2]                                                                                                                                
4558 >---at org.elasticsearch.index.query.QueryShardContext.lambda$toQuery$2(QueryShardContext.java:305) ~[elasticsearch-6.4.2.jar:6.4.2]                                                                                                                            
4559 >---at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:317) ~[elasticsearch-6.4.2.jar:6.4.2]                                                                                                                                     
4560 >---at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:304) ~[elasticsearch-6.4.2.jar:6.4.2]                                                                                                                                     
4561 >---at org.elasticsearch.search.SearchService.parseSource(SearchService.java:724) ~[elasticsearch-6.4.2.jar:6.4.2]                                                                                                                                              
4562 >---at org.elasticsearch.search.SearchService.createContext(SearchService.java:575) ~[elasticsearch-6.4.2.jar:6.4.2]                                                                                                                                            
4563 >---at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:551) ~[elasticsearch-6.4.2.jar:6.4.2]                                                                                                                                      
4564 >---at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:347) ~[elasticsearch-6.4.2.jar:6.4.2]                                                                                                                                        
4565 >---at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:333) ~[elasticsearch-6.4.2.jar:6.4.2]                                                                                                                                             
4566 >---at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:329) ~[elasticsearch-6.4.2.jar:6.4.2]                                                                                                                                             
4567 >---at org.elasticsearch.search.SearchService$3.doRun(SearchService.java:1019) ~[elasticsearch-6.4.2.jar:6.4.2]                                                                                                                                                 
4568 >---at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:723) ~[elasticsearch-6.4.2.jar:6.4.2]                                                                                                  
4569 >---at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.4.2.jar:6.4.2]                                                                                                                                 
4570 >---at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41) ~[elasticsearch-6.4.2.jar:6.4.2]                                                                                                                                     
4571 >---at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.4.2.jar:6.4.2]                                                                                                                                 
4572 >---at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_191]                                                                                                                                                           
4573 >---at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_191]                                                                                                                                                           
4574 >---at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_191]

**Comment by wmelton** [comment]
Are you actually running ES6.4.2 or did you just put that version in the Pom file?

If you are running ES on localhost with default config, you can `curl -XGET 'localhost:9200'` to get the version you are running.


Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
