### ISSUE TITLE
[cast exception] Getting cast exception when passed vector has zero or an integer value

### ISSUE THREAD

**Issue by coolmaksat** [StaySense/fast-cosine-similarity#5]
We use org.json to generate a query and when we dump the query to string it turns double zeros to integers which causes the cast exception here:

https://github.com/StaySense/fast-cosine-similarity/blob/master/src/main/java/com/staysense/fastcosinesimilarity/FastCosineSimilarityPlugin.java#L98

**Comment by wmelton** [comment]
You need to ensure all vectors are a vector of doubles, not ints.

Otherwise you need to convert vectors to string embeddings as described in the repo’s readme.
