### ISSUE TITLE
Stuck at downloading sonatype packages during maven build

### ISSUE THREAD

**Issue by durakkerem** [StaySense/fast-cosine-similarity#9]
During build, process gets stuck at downloading sonatype archives. Below is one of the files that are not available thus causing build to not continue.

https://oss.sonatype.org/content/repositories/snapshots/org/apache/lucene/lucene-core/7.4.0/lucene-core-7.4.0.pom

My maven version: "3.6.0"
Java version: "1.8.0_201"

**Comment by wmelton** [comment]
@durakkerem - You shouldn't need to build, there is a compiled version already available in the repo. If you are working on a custom implementation, I can't help you with any changes made that could be breaking the build.

https://github.com/StaySense/fast-cosine-similarity/tree/master/target/releases

**Comment by durakkerem** [comment]
My ES version was 6.4.3 therefore I needed to re-compile with pom file updated. I was able to compile by manually adding the necessary files that cannot be downloaded during compilation.

**Comment by wmelton** [comment]
@durakkerem - ahhh that makes sense, we've never built for 6.4.3. 

Will try to update this soon to build for the latest version of ES. 

Did you have to make any modifications to your POM file for this to work?

**Comment by durakkerem** [comment]
I've only updated the version in the POM file.
